### ISSUE TITLE
Textures Needed

### ISSUE THREAD

**Issue by pauljoda** [TeamBR-Modding/ProjectDN#1]
Update as progressing 
- Day and night ingot and solid block

**Comment by Dyonovan** [comment]
6 solid blocks. 3 day 3 night  - 3 levels each

**Comment by Dyonovan** [comment]
Need a Crystal Seed and 4 stages of a crystal growth

**Comment by Dominance** [comment]
Got the 4 stages of crystal growth done, The seed is done, What did you have in mine for the 6 solid blocks?

**Comment by Parcipal** [comment]
Seed item is in the texturedump
Solid Blocks of the metals
